theme: jekyll-theme-cayman
title: Jorbs's Wanderer Trilogy
description: The Wanderer, Cull, and Explorer. A Slay the Spire mod inspired by Jorbs and co-developed by the community.
taglines:
  - The Wanderer, Cull, and Explorer.
  - Inspired by Jorbs and co-developed by the community.
lang: en-US

navigation:
  - title: Download on Steam
    url: https://steamcommunity.com/sharedfiles/filedetails/?id=1997053791
  - title: About
    url: /about
  - title: Credits
    url: /credits
  - title: GitHub
    url: https://github.com/dbjorge/jorbs-spire-mod
  - title: Discord
    url: https://discord.gg/N8mETek
  - title: Design Sheet
    url: https://docs.google.com/spreadsheets/d/1GY0eJsooEp361hWFL2lD-uPVa5-l-7g4f4FtyKs-k7Q